#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/frontend
- name: Run Frontend Container
  docker_container:
    name: frontend
    image: franklinpalai/tp-devops-frontend:latest
    pull: true
    networks:
      - name: proxy-network
    restart_policy: always
    state: started
