#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/database
- name: Run PostgreSQL Container
  docker_container:
    name: database
    image: franklinpalai/tp-devops-database:latest
    pull: true
    networks:
      - name: app-network
    env:
      POSTGRES_DB: "{{ vault_postgres_db }}"
      POSTGRES_USER: "{{ vault_postgres_user }}"
      POSTGRES_PASSWORD: "{{ vault_postgres_password }}"
    restart_policy: always
    state: started
