#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/app
- name: Run Spring Boot API Container
  docker_container:
    name: backend
    image: franklinpalai/tp-devops-simple-api:latest
    pull: true
    networks:
      - name: app-network
      - name: proxy-network
    env:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://database:5432/{{ vault_postgres_db }}"
      SPRING_DATASOURCE_USERNAME: "{{ vault_postgres_user }}"
      SPRING_DATASOURCE_PASSWORD: "{{ vault_postgres_password }}"
    restart_policy: always
    state: started
