#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/app
- name: Run Spring Boot API Container
  docker_container:
    name: backend
    image: franklinpalai/tp-devops-simple-api:latest
    networks:
      - name: app-network
    env:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://database:5432/db"
      SPRING_DATASOURCE_USERNAME: "usr"
      SPRING_DATASOURCE_PASSWORD: "mon_mot_de_passe_secret_kalfa"
    restart_policy: always
    state: started
