spring:
  datasource:
    # Si la variable DB_HOST existe, Spring l'utilise. Sinon, il met 'localhost' par défaut.
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:db}
    username: ${DB_USER:usr}
    password: ${DB_PASSWORD:pwd}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update