#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/proxy
- name: Run Apache HTTPD Proxy Container
  docker_container:
    name: httpd
    image: franklinpalai/tp-devops-httpd:latest
    networks:
      - name: app-network
    ports:
      - "80:80"
    env:
      BACKEND_URL: "backend:8080"
    restart_policy: always
    state: started
