name: CI/CD Pipeline for Franklin Application

on:
  push:
    branches:
      - main
      - develop # 🚀 Permet de tester le pipeline directement depuis ta branche de dev

jobs:
  # ==========================================
  # 1. JOBS DE BUILD ET PUSH DOCKER
  # ==========================================

  build-and-push-database:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Database image
        uses: docker/build-push-action@v5
        with:
          context: ./database
          push: true
          tags: franklinpalai/tp-devops-database:latest

  build-and-push-backend:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: franklinpalai/tp-devops-simple-api:latest

  build-and-push-httpd:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push HTTPD image
        uses: docker/build-push-action@v5
        with:
          context: ./httpd
          push: true
          tags: franklinpalai/tp-devops-httpd:latest

  # ==========================================
  # 2. JOB DE DÉPLOIEMENT CONTINU (CD)
  # ==========================================

  deploy:
    needs: [build-and-push-database, build-and-push-backend, build-and-push-httpd]
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape A : Configuration de la clé SSH privée sur le Runner pour se connecter au VPS
      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      # Étape B : Installation d'Ansible sur le Runner GitHub Actions
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      # Étape C : Exécution du Playbook en transmettant le mot de passe du Vault via un script éphémère
      - name: Run Ansible Playbook with Vault
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: |
          # 1. Création du script éphémère pour renvoyer le mot de passe du coffre
          echo '#!/bin/bash' > vault_pass.sh
          echo 'echo "$ANSIBLE_VAULT_PASSWORD"' >> vault_pass.sh
          chmod +x vault_pass.sh
          
          # 2. Lancement d'Ansible avec le pointeur sur ce script
          ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml --vault-password-file ./vault_pass.sh
          
          # 3. Nettoyage du script
          rm vault_pass.sh